import React from 'react';
import { MonitorPlay, PlayCircle } from 'lucide-react';
import { useDB } from '../../hooks/useDB';
import { useAuth } from '../../contexts/AuthContext';
import { useActiveBatch } from '../contexts/ActiveBatchContext';
import { isTargetedToStudent } from '../../utils/recipientTargeting';

export default function TodaysSession() {
  const db = useDB(); const { studentProfile } = useAuth(); const { enrolledBatches } = useActiveBatch();
  const now = Date.now(); const todayKey = new Date().toISOString().slice(0, 10);
  const sessions = (db.batchSessions || []).filter(session => enrolledBatches.some(batch => batch.id === session.batchId) && isTargetedToStudent(session, studentProfile) && ((session.sessionDateTime || session.date || '').slice(0, 10) === todayKey || session.status === 'Live')).sort((a, b) => new Date(a.sessionDateTime || a.createdAt || 0).getTime() - new Date(b.sessionDateTime || b.createdAt || 0).getTime());
  return <div className="p-4 sm:p-8 space-y-6 max-w-4xl"><div><h2 className="text-2xl font-display font-extrabold text-slate-800 tracking-tight">Today's Sessions</h2><p className="text-slate-500 text-sm mt-1">All sessions available to you across your enrolled batches.</p></div>
    {!enrolledBatches.length ? <Empty message="No batch assigned yet." /> : !sessions.length ? <Empty message="No sessions scheduled for today." /> : sessions.map(session => { const batch = enrolledBatches.find(item => item.id === session.batchId); const recording = (db.recordings || []).find((item: any) => item.batchId === session.batchId && (item.sessionId === session.id || item.title === session.title || item.title === session.topic)); return <div key={session.id} className="p-6 border border-slate-200 rounded-2xl bg-white shadow-sm"><span className="text-xs font-bold uppercase tracking-wider text-blue-700 bg-blue-100 px-3 py-1 rounded-md">{session.status || (new Date(session.sessionDateTime || 0).getTime() <= now ? 'Live' : 'Upcoming')}</span><h3 className="text-xl font-bold text-slate-800 mt-4">{session.title || session.topic}</h3><p className="text-sm text-slate-500 mt-2">{batch?.course} • {batch?.name} • Mentor: {batch?.mentor || 'Assigned mentor'}</p><p className="text-sm text-slate-500 mt-1">{session.platform || 'Meeting'} • {session.sessionDateTime ? new Date(session.sessionDateTime).toLocaleString() : `${session.date || ''} ${session.time || ''}`}</p><div className="mt-6 flex flex-wrap gap-3">{session.meetingLink && <a href={session.meetingLink} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[#1763B6] hover:bg-[#145096] text-white px-5 py-3 rounded-lg font-bold"><MonitorPlay className="w-5 h-5" />Join Session</a>}{(recording?.videoUrl || session.recordingUrl) && <a href={recording?.videoUrl || session.recordingUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-[#1763B6] text-[#1763B6] px-5 py-3 rounded-lg font-bold"><PlayCircle className="w-5 h-5" />View Recording</a>}</div></div>})}
  </div>;
}
function Empty({ message }: { message: string }) { return <div className="p-10 text-center bg-white rounded-2xl border border-slate-100 shadow-sm text-slate-500"><MonitorPlay className="w-12 h-12 text-slate-200 mx-auto mb-3" />{message}</div>; }
